### ISSUE TITLE
Add JSHint and JSCS

### ISSUE THREAD

**Issue by arthurvr** [h5bp/Effeckt.css#314]
To keep things clean. Preferably running as part of CI so we don't land PRs that aren't quite okay.

We have a style guide in the wiki but we tend to not follow it always. trailing commas, trailing whitespace and many other things are pretty common in the JavaScript codebase.

**Comment by ShashankaNataraj** [comment]
+1 @arthurvr Can I take this task up? :dancer:

**Comment by arthurvr** [comment]
@ShashankaNataraj If nobody from the team has any complaints, why not? Thanks!

**Comment by ShashankaNataraj** [comment]
@grayghostvisuals @arthurvr Just one request though, there are issues in this repo without any labels attached to them. Could someone from the h5bp core team kindly add labels to all the open issues? I see many people interested in this project but not a whole lot of PR's, lets make potential contributors' job easier!

**Comment by arthurvr** [comment]
> Can I take this task up? :dancer:

Is there still interest in picking this up?

**Comment by WellingGuzman** [comment]
This would be a good to have @ShashankaNataraj

**Comment by ShashankaNataraj** [comment]
@arthurvr @WellingGuzman :+1: Yes there is still interest in doing this! I will be pushing commits here and asking for you guys to review the jscsrc file once Im done. I pushed in a commit yesterday, will be pushing in more in the coming days.

**Comment by ShashankaNataraj** [comment]
This is the checklist Im using for this task, this checklist will be updated with the latest changes until I make a PR for all of these:

- [ ] Add .jshintrc
  - [ ] 
- [ ] Add .jscsrc
  - [ ] Use two space indent
  - [ ] Put brakes { after rule declarations/function name/while/for/etc.
  - [ ] Put spaces between rule declarations/function name/while/for/etc and brakes {.
  - [ ] Put spaces after : in property declarations/objects definitions.
  - [ ] Use double slash // for comments block (instead of /* */) and put spaces after double slash.
  - [ ] Any , and ; must not have preceding space.
  - [ ] Use Spaces after and before ( and ) and [ and ].
  - [ ] Use Spaces after and before = assigning values.
  - [ ] Don't use spaces after unary operators such as ! or ++.
  - [ ] Use space after , in arguments variable.
  - [ ] Declaring Objects using multi-line.
  - [ ] Declaring variables using multi-line.
  - [ ] When chained methods make long lines, divide each method on mutiple lines.
  - [ ] Use $ in front of a variable if it's a jquery object.
  - [ ] Always use semicolons ;.

**Comment by arthurvr** [comment]
@ShashankaNataraj That sounds like a great todo list :dancer: Another point is to make sure that it runs in CI using Travis.

**Comment by ShashankaNataraj** [comment]
@arthurvr Thanks :+1: Will make sure to check if JSCS and JSHint run in Travis CI before making a PR.

**Comment by ShashankaNataraj** [comment]
@arthurvr @WellingGuzman @benschwarz 202 code style errors found :stuck_out_tongue_winking_eye:

**Comment by arthurvr** [comment]
Let's first set it up and then we can fix all the errors in a new issue.

**Comment by ShashankaNataraj** [comment]
@arthurvr exactly what i meant :+1:

**Comment by ShashankaNataraj** [comment]
@arthurvr Travis CI is now integrated and triggers the `grunt quality` task from the build on every checkin.

![screenshot_2015-06-12_11-10-27](https://cloud.githubusercontent.com/assets/650317/8124130/f83926b2-10f3-11e5-8f6c-43db4f9f0eb1.png)

Is this good enough to raise a PR?

**Comment by hzoo** [comment]
@ShashankaNataraj You can autofix most of the whitespace errors now with `--fix` http://jscs.info/overview.html#cli

**Comment by arthurvr** [comment]
> Is this good enough to raise a PR?

Haven't looked at your code yet but feel free to submit a PR :) PRs are meant to be reviewed :p

**Comment by ShashankaNataraj** [comment]
@hzoo thanks for the info, will do, but as @arthurvr mentioned above I'll be doing it as part of another issue after this one reaches closure.

@arthurvr alright raising a pr now, hope you guys take a look.

**Comment by ShashankaNataraj** [comment]
@hzoo Have added requireDollarBeforejQueryAssignment as mentioned in the jscs thread. Thanks for pointing that out!
