### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by morenoh149** [h5bp/Effeckt.css#319]
Just wondering what's the status of the project. With over 10K stars.

**Comment by dennisgaebel** [comment]
Agreed. It is on hold at the moment due to the community being divided on the trajectory.

**Comment by abacaj** [comment]
Looks dead to me, last commit over 10 months ago quite a shame.

**Comment by joshkpeterson** [comment]
In what ways is it "Not quite ready for prime time" ?

**Comment by grayghostvisuals** [comment]
@joshkpeterson It means the code isn't production ready and packaged in a way to distribute to authors. It's a "use at your own risk" kind of thing.

**Comment by AaronLayton** [comment]
I have been here since the project inception and yeah definitely no forward movement on this. 

I just ended up using sections of this in my personal projects as at the time, there was a conversation about how to package each section. I think it just got over complicated for what should just be some CSS classes that control animation, a bit of JS to show how to use it or set a state.

From what I remember, modules were being made that do full Modal control or even tab systems. This was not what I gathered the original intent of this project to be. Originally is was

*A Performant Transitions and Animations Library*

It ended up trying to be more than that don't you think? IMO Animate.css gets this correct. What Effeckt needed to be was all the parts missing, like applying those animations to buttons, page transitions, animation states.

It would still be good to see this project move forward, but I think it would need redefining what role it is trying to play.

**Comment by grayghostvisuals** [comment]
> From what I remember, modules were being made that do full Modal control or even tab systems

@AaronLayton Those modules/components you're referencing were made for a reason and still follow the credo "A Performant Transitions and Animations Library." Each have their own markup pattern for said modules/components.

That said there still is no reason why this project can't be packaged for authors in a way and remain a "A Performant Transitions and Animations Library." See [https://github.com/h5bp/Effeckt.css/issues/103](https://github.com/h5bp/Effeckt.css/issues/103)

**Comment by AaronLayton** [comment]
@grayghostvisuals oh yeah they had their reasons at the time of being made. But creating a module that lets people implement a Modal, is that really a Transition and Animations library? Just my opinion on it but not a massive deal. I agree that anyone wanting to use this would need to see the example uses ;-)

I guess the big questions is what happens now? Do we move on with this, is there a way we can finish this project, or narrow down the scope to just a few modules / transitions.

**Comment by grayghostvisuals** [comment]
> is that really a Transition and Animations library?

Yes and no. Authors will ultimately need the components markup to correlate with the animation assets. To move on I think the scope needs to be less absolute and more accepting of what it can become. It can still be a Transition and Animations library that also includes the components for each case while still maintaining isolated styles and scripts so they can be applied to any component an author desires to use. 

Essentially an author should be able to walk away with the markup, a js file and a css file without having necc. pieces scattered throughout other files that having naming not correlating.

BTW at this time there is no way that has been determined how to decide if the animation is performant or included with the project so contributors can determine if the effect is in fact performant.

**Comment by morenoh149** [comment]
@grayghostvisuals I'm assuming you could use a selenium webdriver or something that can read out the frames per second on the page. You would need a suite of tests like this that would output benchmark numbers and warn the project authors if an animation is too slow. I also think that animations on mobile web got "good enough" where this project may not be as necessary as originally thought.

**Comment by grayghostvisuals** [comment]
@morenoh149 If you would like to open another issue thread to discuss selenium/benchmark perf tooling that would be fine but for now I'll be closing this issue before it gets away from us and beyond the scope of the topic.
